name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
  
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_IP_ADDRESS }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port : ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ secrets.SSH_PROJECT_PATH }}
          sudo chmod 777 -R ${{ secrets.SSH_PROJECT_PATH }}/storage/
          sudo chmod 777 -R ${{ secrets.SSH_PROJECT_PATH }}/bootstrap/
    
    
    # - name: Deploy to server via ssh
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: ${{ secrets.SSH_IP_ADDRESS }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     password: ${{ secrets.SSH_PASSWORD }}
    #     port : ${{ secrets.SSH_PORT }}
    #     script: "cd ${{ secrets.SSH_PROJECT_PATH }} && sh ./deploy.sh"
