name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@main
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # - name: Permission given
    #   run: chmod 777 -R storage bootstrap

    - name: Optimize applications
      run: php artisan optimize      

    - name: Deploy to ssh server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SSH_IP_ADDRESS }}
        REMOTE_USER: ${{ secrets.SSH_USERNAME }}
        REMOTE_PORT: ${{ secrets.SSH_PORT }}
        TARGET: /var/www/html/php74-web/laravelcicd.project-demo.info/
        SSH_CMD_ARGS : "-o StrictHostKeyChecking=no"

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_IP_ADDRESS }}
        username: ${{ secrets.SSH_USERNAME }}
        # password: ${{ secrets.SSH_PASSWORD }}
        port : ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            cd /var/www/html/php74-web/laravelcicd.project-demo.info/
            php artisan down
            chmod 777 -R storage bootstrap
            php artisan up
  