name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@main

      
    # - name: Deploy to ssh server
    #   uses: easingthemes/ssh-deploy@v2.1.5
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #     REMOTE_HOST: ${{ secrets.SSH_IP_ADDRESS }}
    #     REMOTE_USER: ${{ secrets.SSH_USERNAME }}
    #     REMOTE_PORT: ${{ secrets.SSH_PORT }}
    #     TARGET: ${{ secrets.SSH_PROJECT_PATH }}
    #     SSH_CMD_ARGS : "-o StrictHostKeyChecking=no"

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_IP_ADDRESS }}
        username: ${{ secrets.SSH_USERNAME }}
        # password: ${{ secrets.SSH_PASSWORD }}
        port : ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
            cd ${{ secrets.SSH_PROJECT_PATH }}
            sh deploy.sh
            
  