name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    
    - uses: actions/checkout@v4

    - name: Deploy to server via ssh
      uses: appleboy/ssh-action@v.0.1.3 
      with:
        host: ${{ secrets.SSH_IP_ADDRESS }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: "cd /var/www/html/laravel-cicd/ && sh ./deploy.sh"
